// react-todo/src/components/AddTodo.js
import React, { Component } from 'react'

export class AddTodo extends Component {
    state = {
        title: ''
    }

    onChange = (e) => this.setState({
        title: e.target.value
    })

    onSubmit = (e) => {
        e.preventDefault()
        this.props.addTodo(this.state.title)
        this.setState({title: ''})
    }
    render() {
        return (
            <form style={{display: 'flex'}} onSubmit={this.onSubmit}>
                <input 
                type='text' 
                name='title' 
                placeholder='add todo' 
                style={{flex : '10'}} 
                padding='5px' value = {this.state.title}
                onChange={this.onChange}/>

                <input 
                type='submit' 
                value='submit' 
                className='btn' 
                style={{flex: '1'}}/>
            </form>
        )
    }
}

export default AddTodo

// vuejs/vue-proj/src/components/AddTodo.vue
<template>
  <div>
      <form v-on:submit="addTodo">
          <input type="text" name="title" placeholder="Add todo..." v-model="title"/>
          <input type="submit" name="submit" class="btn" />
      </form>
  </div>
</template>

<script>
export default {
    name:"AddTodo",
    data(){
        return{
            title: ''
        }
    },
    methods:{
        addTodo(e){
            e.preventDefault()
            const newTodo = {
                title : this.title,
                completed: false
            }

            // drill up to parent
            this.$emit('add-todo', newTodo)
            this.title = ''
        }
    }

}
</script>

<style scoped>
 form{
     display: flex;
 }

 input[type="text"]{
     flex: 10;
     padding: 5px
 }

 input[type="submit"]{
     flex: 2;
 }
</style>
