// vuejs/vue-proj/src/components/Todos.vue
<template>
  <div>
    <h1>Todos</h1>
    <div v-for="todo in todos" v-bind:key="todo.id">
      <TodoItem v-bind:todo="todo"/>
    </div>
  </div>
</template>

<script>
import TodoItem from './TodoItem.vue'

export default {
  name: "Todos",
  components:{
      TodoItem
  },
  props: ["todos"]
};
</script>

<style scoped>
</style>>

// react-todo/src/components/Todos.js
import React, {Component} from 'react'
import TodoItem from './TodoItem'
import PropTypes from 'prop-types'

class Todos extends Component {
    render(){
        return this.props.todos.map(
            (todo) => (
                <TodoItem key = {todo.id} todo = {todo}/>
            )
        )
    }
}

//PropTypes
Todos.propTypes = {
    todos : PropTypes.array.isRequired
}

export default Todos;
