// react-todo/src/components/AddTodo.js
import React, { Component } from 'react'

export class AddTodo extends Component {
    state = {
        title: ''
    }

    onChange = (e) => this.setState({
        title: e.target.value
    })

    onSubmit = (e) => {
        e.preventDefault()
        this.props.addTodo(this.state.title)
        this.setState({title: ''})
    }
    render() {
        return (
            <form style={{display: 'flex'}} onSubmit={this.onSubmit}>
                <input 
                type='text' 
                name='title' 
                placeholder='add todo' 
                style={{flex : '10'}} 
                padding='5px' value = {this.state.title}
                onChange={this.onChange}/>

                <input 
                type='submit' 
                value='submit' 
                className='btn' 
                style={{flex: '1'}}/>
            </form>
        )
    }
}

export default AddTodo

// vue-vuex/src/components/AddTodo.vue
<template>
  <div>
    <h3>add todo</h3>
    <div class="add">
      <form v-on:submit="onSubmit">
        <input type="text" v-model="title" placeholder="Add todos ....">
        <input type="submit" value="submit">
      </form>
    </div>
  </div>
</template>

<script>
import { mapActions} from 'vuex'

export default {
  name: 'AddTodo',
  data(){
    return{
      title : ''
    }
  },
  methods: {
    ...mapActions(['addTodo']),
    onSubmit(e){
      e.preventDefault()
      this.addTodo(this.title)
      console.log(this.title)
    }
  }
}
</script>

<style scoped>
  form{
    display: flex;
  }

  input[type="text"]{
    flex: 10;
    padding: 10px;
    border: 1px solid lightblue;
    outline: 0;
  }

  input[type="submit"]{
    flex: 2;
    background: lightgreen;
    color: white;
    border: 1px lightgreen solid;
    cursor: pointer;
  }
  
  input[type="submit"]:hover{
    background: darkcyan;
  }
</style>
