// react-todo/src/components/layout/Header.js
import React from 'react'
import {Link} from 'react-router-dom'

function Header() {
    return (
        <header style = {HeaderStyle}>
            <h1>Todo List</h1>
            <Link to="/" style={linkStyle}>Home</Link> | <Link to="/about" style={linkStyle}>About</Link>
        </header>
    )
}

const HeaderStyle = {
    background : '#333',    
    textAlign : 'center',
    color : '#fff',
    padding : '10px'
}

const linkStyle = {
    color : '#fff'
}
export default Header

// vuejs/vue-proj/src/components/layout/Header.vue
<template>
  <header class="header">
    <h1>TodoList</h1>
    <div id="nav">
      <router-link to="/">Home</router-link>|
      <router-link to="/about">About</router-link>
    </div>
  </header>
</template>

<script>
export default {
  name: "Header"
};
</script>

<style scoped>
.header {
  background: grey;
  color: white;
  text-align: center;
  padding: 10px;
}

.header a {
    padding: 0;
}
</style>
